//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wildfire_ICS_Assist.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wildfire_ICS_Assist.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new organization chart role.
        /// </summary>
        internal static string AddOrgChartRole {
            get {
                return ResourceManager.GetString("AddOrgChartRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles cannot be set to report to themselves..
        /// </summary>
        internal static string CantReportToSelf {
            get {
                return ResourceManager.GetString("CantReportToSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a name for the contact before saving..
        /// </summary>
        internal static string EditContactValidationError {
            get {
                return ResourceManager.GetString("EditContactValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_137_cogwheel {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_137_cogwheel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_145_folder_open {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_145_folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_151_square_edit {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_151_square_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_152_square_new_window {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_152_square_new_window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_152_square_new_window_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_152_square_new_window_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_159_thumbnails_list {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_159_thumbnails_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_16_print {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_16_print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_17_bin {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_17_bin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_193_circle_empty_remove {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_193_circle_empty_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_199_save {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_199_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_210_circle_empty_right {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_210_circle_empty_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_221_chevron_down_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_221_chevron_down_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_222_chevron_up_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_222_chevron_up_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_223_chevron_left {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_223_chevron_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_224_chevron_right {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_224_chevron_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_224_chevron_right_double {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_224_chevron_right_double", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_234_calculator {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_234_calculator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_234_calculator_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_234_calculator_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_234_calculator1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_234_calculator1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_250_eraser {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_250_eraser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_278_cutlery {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_278_cutlery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_28_search {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_28_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_29_cars {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_29_cars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_30_clipboard {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_30_clipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_302_square_download {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_302_square_download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_31_pencil {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_31_pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_33_access_point {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_33_access_point", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_371_plus {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_371_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_371_plus_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_371_plus_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_372_minus {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_372_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_399_import {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-399-import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_4_user {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_4_user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_4_user_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_4_user_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_40_notes {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_40_notes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_400_export {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_400_export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_424_blackboard {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_424_blackboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_431_log_in {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_431_log_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_432_log_out {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_432_log_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_475_sort_numerically_alt {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_475_sort_numerically_alt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_477_sort_attributes_alt {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_477_sort_attributes_alt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_52_eye {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-52-eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_532_user_family {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_532_user_family", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_537_progress {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_537_progress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_539_barcode {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_539_barcode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_540_qr_code {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_540_qr_code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_55_clock {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_55_clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_556_flash {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_556_flash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_557_flash_automatic {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_557_flash_automatic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_559_target {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_559_target", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_58_history {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_58_history", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_592_map {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_592_map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_61_compass {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_61_compass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_611_copy_duplicate {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_611_copy_duplicate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_635_circle_question {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_635_circle_question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_638_triangle_alert_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_638_triangle_alert_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_670_dashboard {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_670_dashboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_739_check {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_739_check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_740_hash {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_740_hash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_761_sync_grey {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_761_sync_grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_763_sync_check_green {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_763_sync_check_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_801_file_plus {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_801_file_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_82_refresh {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_82_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_849_computer_network {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_849_computer_network", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_876_palette_package {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_876_palette_package", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_89_book_address {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_89_book_address", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_931_speech_bubble_question_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_931_speech_bubble_question_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_931_speech_bubble_question_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_931_speech_bubble_question_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_931_speech_bubble_question_sm {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_931_speech_bubble_question_sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_965_layers_plus {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_965_layers_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_976_globe_data {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_976_globe_data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_978_map_cadastral {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_978_map_cadastral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_987_switch_off {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_987_switch_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_988_switch_on {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_988_switch_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_refresh_comms {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_refresh_comms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_calculate_and_output {
            get {
                object obj = ResourceManager.GetObject("glyphicons_calculate_and_output", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_filetypes_9_file_spreadsheet {
            get {
                object obj = ResourceManager.GetObject("glyphicons_filetypes_9_file_spreadsheet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ics_ca_sq_white {
            get {
                object obj = ResourceManager.GetObject("ics_ca_sq_white", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ics_canada_logo {
            get {
                object obj = ResourceManager.GetObject("ics-canada-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have made an invalid choice for who this role reports to.  The role you have selected is further down the org chart under the current role..
        /// </summary>
        internal static string InvalidReportsToRole {
            get {
                return ResourceManager.GetString("InvalidReportsToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully imported [IMPORT] new members, and updated [UPDATE] existing members..
        /// </summary>
        internal static string MembersImported {
            get {
                return ResourceManager.GetString("MembersImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must complete all required fields in order to proceed.  Required fields are marked with a *..
        /// </summary>
        internal static string MissingInformationValidationError {
            get {
                return ResourceManager.GetString("MissingInformationValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No members were imported or updated.  Please ensure you have configured the options here correctly, and selected the correct spreadsheet file..
        /// </summary>
        internal static string NoMembersImported {
            get {
                return ResourceManager.GetString("NoMembersImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this role cannot be edited or removed as it is essential to ICS organizational structure.
        /// </summary>
        internal static string ProtectedRole {
            get {
                return ResourceManager.GetString("ProtectedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Select a saved contact-.
        /// </summary>
        internal static string SelectSavedContact {
            get {
                return ResourceManager.GetString("SelectSavedContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected item(s)?.
        /// </summary>
        internal static string SureDelete {
            get {
                return ResourceManager.GetString("SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete items?.
        /// </summary>
        internal static string SureDeleteTitle {
            get {
                return ResourceManager.GetString("SureDeleteTitle", resourceCulture);
            }
        }
    }
}
