//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wildfire_ICS_Assist.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wildfire_ICS_Assist.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new organization chart role.
        /// </summary>
        internal static string AddOrgChartRole {
            get {
                return ResourceManager.GetString("AddOrgChartRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSureTitle {
            get {
                return ResourceManager.GetString("AreYouSureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Artboard_1 {
            get {
                object obj = ResourceManager.GetObject("Artboard 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Artboard_1_2x {
            get {
                object obj = ResourceManager.GetObject("Artboard 1@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles cannot be set to report to themselves..
        /// </summary>
        internal static string CantReportToSelf {
            get {
                return ResourceManager.GetString("CantReportToSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CIAPP_LOGO_v3 {
            get {
                object obj = ResourceManager.GetObject("CIAPP-LOGO-v3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CIAPP_LOGO_v3_transparent {
            get {
                object obj = ResourceManager.GetObject("CIAPP-LOGO-v3-transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CIAPPFormSet_01 {
            get {
                object obj = ResourceManager.GetObject("CIAPPFormSet-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CIAPPFormSet_02 {
            get {
                object obj = ResourceManager.GetObject("CIAPPFormSet-02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Unified Command roles?.
        /// </summary>
        internal static string ClearUnifiedCommandRolesTitle {
            get {
                return ResourceManager.GetString("ClearUnifiedCommandRolesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first remove or reassign any roles that report to this one before removing it..
        /// </summary>
        internal static string DeleteSubordinateRoles {
            get {
                return ResourceManager.GetString("DeleteSubordinateRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a name for the contact before saving..
        /// </summary>
        internal static string EditContactValidationError {
            get {
                return ResourceManager.GetString("EditContactValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To edit Branches, Divisions, Groups, Strike Teams, or Task Forces, please use the &quot;Assignment List&quot; tool instead..
        /// </summary>
        internal static string EditInAssignmnetList {
            get {
                return ResourceManager.GetString("EditInAssignmnetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a name for the role you are adding to the organization chart.
        /// </summary>
        internal static string EmptyRoleError {
            get {
                return ResourceManager.GetString("EmptyRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EquipOp {
            get {
                object obj = ResourceManager.GetObject("EquipOp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_11_envelope {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-11-envelope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_137_cogwheel {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_137_cogwheel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_145_folder_open {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_145_folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_151_square_edit {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_151_square_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_152_square_new_window {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_152_square_new_window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_152_square_new_window_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_152_square_new_window_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_159_thumbnails_list {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_159_thumbnails_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_16_print {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_16_print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_17_bin {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_17_bin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_193_circle_empty_remove {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_193_circle_empty_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_196_circle_empty_info {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-196-circle-empty-info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_199_save {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_199_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_210_circle_empty_right {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_210_circle_empty_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_217_lock {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-217-lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_217_lock_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-217-lock@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_218_lock_open {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-218-lock-open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_218_lock_open_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-218-lock-open@2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_221_chevron_down_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_221_chevron_down_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_222_chevron_up_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_222_chevron_up_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_223_chevron_left {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_223_chevron_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_224_chevron_right {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_224_chevron_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_224_chevron_right_double {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_224_chevron_right_double", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_234_calculator {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_234_calculator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_234_calculator_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_234_calculator_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_234_calculator1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_234_calculator1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_238_chat_message {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-238-chat-message", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_250_eraser {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_250_eraser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_278_cutlery {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_278_cutlery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_28_search {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_28_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_29_cars {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_29_cars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_292_square_empty_minus {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-292-square-empty-minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_294_square_empty_check {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-294-square-empty-check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_30_clipboard {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_30_clipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_302_square_download {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_302_square_download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_31_pencil {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_31_pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_33_access_point {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_33_access_point", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_35_user_incognito {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-35-user-incognito", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_371_plus {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_371_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_371_plus_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_371_plus_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_372_minus {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_372_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_38_picture {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-38-picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_39_airplane {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-39-airplane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_395_filter {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-395-filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_399_import {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-399-import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_4_user {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_4_user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_4_user_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_4_user_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_40_notes {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_40_notes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_400_export {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_400_export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_41_stats {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-41-stats", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_424_blackboard {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_424_blackboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_431_log_in {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_431_log_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_432_log_out {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_432_log_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_46_calendar {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-46-calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_475_sort_numerically_alt {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_475_sort_numerically_alt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_477_sort_attributes_alt {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_477_sort_attributes_alt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_487_exchange {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-487-exchange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_5_settings_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-5-settings@3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_52_eye {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-52-eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_532_user_family {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_532_user_family", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_537_progress {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_537_progress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_539_barcode {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_539_barcode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_540_qr_code {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_540_qr_code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_55_clock {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_55_clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_556_flash {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_556_flash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_557_flash_automatic {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_557_flash_automatic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_559_target {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_559_target", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_58_history {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_58_history", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_59_truck {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-59-truck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_592_map {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_592_map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_61_compass {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_61_compass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_611_copy_duplicate {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_611_copy_duplicate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_613_paste {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-613-paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_635_circle_question {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_635_circle_question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_638_triangle_alert_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_638_triangle_alert_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_639_octagon_remove_empty_red {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-639-octagon-remove-empty-red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_670_dashboard {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_670_dashboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_730_ambulance {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-730-ambulance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_739_check {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_739_check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_739_check_black {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-739-check-black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_739_check_green {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-739-check-green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_740_hash {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_740_hash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_761_sync_grey {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_761_sync_grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_763_sync_check_green {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_763_sync_check_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_799_chevron_last_left {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-799-chevron-last-left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_801_file_plus {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_801_file_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_809_drop_plus {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-809-drop-plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_82_refresh {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_82_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_841_square_plus {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-841-square-plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_849_computer_network {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_849_computer_network", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_876_palette_package {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_876_palette_package", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_888_redo {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-888-redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_89_addressbook {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_89_addressbook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_89_book_address {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-89-book-address", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_893_user_worker {
            get {
                object obj = ResourceManager.GetObject("glyphicons-basic-893-user-worker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_931_speech_bubble_question_2x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_931_speech_bubble_question_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_931_speech_bubble_question_3x {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_931_speech_bubble_question_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_931_speech_bubble_question_sm {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_931_speech_bubble_question_sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_965_layers_plus1 {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_965_layers_plus1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_976_globe_data {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_976_globe_data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_978_map_cadastral {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_978_map_cadastral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_987_switch_off {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_987_switch_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_988_switch_on {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_988_switch_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_basic_refresh_comms {
            get {
                object obj = ResourceManager.GetObject("glyphicons_basic_refresh_comms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_calculate_and_output {
            get {
                object obj = ResourceManager.GetObject("glyphicons_calculate_and_output", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_filetypes_2_file_rich_text {
            get {
                object obj = ResourceManager.GetObject("glyphicons-filetypes-2-file-rich-text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glyphicons_filetypes_52_folder_video {
            get {
                object obj = ResourceManager.GetObject("glyphicons-filetypes-52-folder-video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HECrew {
            get {
                object obj = ResourceManager.GetObject("HECrew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ics_ca_sq_white {
            get {
                object obj = ResourceManager.GetObject("ics_ca_sq_white", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ics_canada_logo {
            get {
                object obj = ResourceManager.GetObject("ics-canada-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have made an invalid choice for who this role reports to.  The role you have selected is further down the org chart under the current role..
        /// </summary>
        internal static string InvalidReportsToRole {
            get {
                return ResourceManager.GetString("InvalidReportsToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully imported [IMPORT] new personnel, and updated [UPDATE] existing personnel..
        /// </summary>
        internal static string MembersImported {
            get {
                return ResourceManager.GetString("MembersImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must complete all required fields in order to proceed.  Required fields are marked with a *..
        /// </summary>
        internal static string MissingInformationValidationError {
            get {
                return ResourceManager.GetString("MissingInformationValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No members were imported or updated.  Please ensure you have configured the options here correctly, and selected the correct spreadsheet file..
        /// </summary>
        internal static string NoMembersImported {
            get {
                return ResourceManager.GetString("NoMembersImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot switch from Unified Command to a single Incident Commander while the Unified Command roles are filled, or have filled subordinate roles.  Would you like to clear all Unified Command roles automatically?.
        /// </summary>
        internal static string NoSwitchToICWithUCRolesFilled {
            get {
                return ResourceManager.GetString("NoSwitchToICWithUCRolesFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon P_icon {
            get {
                object obj = ResourceManager.GetObject("P_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to proceed?.
        /// </summary>
        internal static string ProceedTitle {
            get {
                return ResourceManager.GetString("ProceedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this role cannot be edited or removed as it is essential to ICS organizational structure.
        /// </summary>
        internal static string ProtectedRole {
            get {
                return ResourceManager.GetString("ProtectedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberta
        ///British Columbia
        ///Manitoba
        ///New Brunswick
        ///Newfoundland and Labrador
        ///Northwest Territories
        ///Nova Scotia
        ///Nunavut
        ///Ontario
        ///Prince Edward Island
        ///Quebec
        ///Saskatchewan
        ///Yukon.
        /// </summary>
        internal static string ProvincesAndTerritoriesEN {
            get {
                return ResourceManager.GetString("ProvincesAndTerritoriesEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedExclaim {
            get {
                object obj = ResourceManager.GetObject("RedExclaim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedExclaimSq {
            get {
                object obj = ResourceManager.GetObject("RedExclaimSq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot delete this role, but you can rename it as needed.  Would you like to rename this role now?.
        /// </summary>
        internal static string RenameInsteadOfDeleteRole {
            get {
                return ResourceManager.GetString("RenameInsteadOfDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename?.
        /// </summary>
        internal static string RenameTitle {
            get {
                return ResourceManager.GetString("RenameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP! You are about to replace the incident currently on this machine with a current copy of the one on the server computer. You will lose any changes you’ve made here that are not already reflected there. There is no way to undo this. Are you very sure you want to proceed?.
        /// </summary>
        internal static string RequestIncidentFromServer {
            get {
                return ResourceManager.GetString("RequestIncidentFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to request all of the options from the server?\r\n\r\n*These options will replace any already on this machine, including personnel, templates, general options, saved communications channels, and so forth..
        /// </summary>
        internal static string RequestOptionsFromServer {
            get {
                return ResourceManager.GetString("RequestOptionsFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string RequiredNote {
            get {
                return ResourceManager.GetString("RequiredNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed required fields.
        /// </summary>
        internal static string RequiredTitle {
            get {
                return ResourceManager.GetString("RequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Select a saved contact-.
        /// </summary>
        internal static string SelectSavedContact {
            get {
                return ResourceManager.GetString("SelectSavedContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are sure you want to cancel and lose any unsaved changes on this screen?.
        /// </summary>
        internal static string SureCancel {
            get {
                return ResourceManager.GetString("SureCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected item(s)?.
        /// </summary>
        internal static string SureDelete {
            get {
                return ResourceManager.GetString("SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete items?.
        /// </summary>
        internal static string SureDeleteTitle {
            get {
                return ResourceManager.GetString("SureDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing this resource from the crew will leave it in the Check In list as a single resource. You can then modify its check-in details as needed, check it out, etc. Are you sure you want to proceed with this change?.
        /// </summary>
        internal static string SureRemoveFromCrew {
            get {
                return ResourceManager.GetString("SureRemoveFromCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the selected image?.
        /// </summary>
        internal static string SureRemoveImage {
            get {
                return ResourceManager.GetString("SureRemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Image?.
        /// </summary>
        internal static string SureRemoveImageTitle {
            get {
                return ResourceManager.GetString("SureRemoveImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter valid coordinates, or leave the coordinate field(s) blank in order to proceed. You may enter latitude and longitude, UTM, or MGRS..
        /// </summary>
        internal static string ValidCoordinatesRequired {
            get {
                return ResourceManager.GetString("ValidCoordinatesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a NOTAM defined by a polygon, you must enter at least 3 valid coordinates..
        /// </summary>
        internal static string ValidPolygonCoordinatesRequired {
            get {
                return ResourceManager.GetString("ValidPolygonCoordinatesRequired", resourceCulture);
            }
        }
    }
}
